        <table class="table">
        <tr>
        <th>
        アーティスト名
        </th>
        <th>
        ジャンル
        </th>
        <th>
        国名
        </th>
        <th>
        活動期間
        </th>
        <th>
        記事数
        </th>
        <th>
        最終更新
        </th>
        </tr>
        <!-- tdテーブルの追加 -->
        <tr>
        <td>
        Prince
        </td>
        <td>
        アメリカ
        </td>
        <td>
        60年～70年
        </td>
        <td>
        3
        </td>
        <td>
        2014/3/31
        </td>
        <td>
        2014/3/31
        </td>
        </tr>
        <!-- //tdテーブル追加 -->
        </table>